import { Location } from "@shared/schema";

// This file is only used during development if the backend isn't available
export const mockLocations: Location[] = [
  {
    id: 1,
    name: "Paws & Coffee",
    description: "A cozy coffee shop with outdoor seating and dog treats",
    category: "cafe",
    address: "123 Main St, Downtown",
    latitude: 37.7749,
    longitude: -122.4194,
    rating: 4.2,
    reviewCount: 120,
    imageUrl: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?ixlib=rb-4.0.3",
    features: "Water bowls provided,Outdoor seating,Pet treats",
    distanceMiles: 0.3,
  },
  {
    id: 2,
    name: "Barking Bistro",
    description: "Restaurant with dedicated dog-friendly seating area",
    category: "restaurant",
    address: "456 Park Ave, Downtown",
    latitude: 37.7739,
    longitude: -122.4312,
    rating: 4.9,
    reviewCount: 203,
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?ixlib=rb-4.0.3",
    features: "Special dog menu,Patio seating,Water bowls",
    distanceMiles: 0.7,
  },
  {
    id: 3,
    name: "Central Bark Park",
    description: "Large off-leash dog park with separate areas for small and large dogs",
    category: "park",
    address: "789 Green St, Downtown",
    latitude: 37.7829,
    longitude: -122.4324,
    rating: 4.8,
    reviewCount: 356,
    imageUrl: "https://images.unsplash.com/photo-1551730459-92db2a308d6a?ixlib=rb-4.0.3",
    features: "Off-leash area,Water fountains,Waste stations,Separate area for small dogs",
    distanceMiles: 1.2,
  },
  {
    id: 4,
    name: "Tail Waggers Pet Shop",
    description: "Pet supply store that welcomes dogs inside",
    category: "shop",
    address: "321 Oak St, Downtown",
    latitude: 37.7869,
    longitude: -122.4254,
    rating: 4.5,
    reviewCount: 89,
    imageUrl: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?ixlib=rb-4.0.3",
    features: "Dogs allowed inside,Free samples,Pet measuring station",
    distanceMiles: 0.5,
  },
  {
    id: 5,
    name: "Pup-Friendly Brewery",
    description: "Craft brewery with covered outdoor patio for dogs",
    category: "restaurant",
    address: "555 Brew St, Downtown",
    latitude: 37.7849,
    longitude: -122.4294,
    rating: 4.7,
    reviewCount: 175,
    imageUrl: "https://images.unsplash.com/photo-1516647355350-5318acd8c083?ixlib=rb-4.0.3",
    features: "Dog-friendly patio,Water stations,Occasional pet events",
    distanceMiles: 0.8,
  },
  {
    id: 6,
    name: "Canine Commons Park",
    description: "Small neighborhood park with dedicated dog area",
    category: "park",
    address: "222 Elm St, Downtown",
    latitude: 37.7879,
    longitude: -122.4159,
    rating: 4.3,
    reviewCount: 97,
    imageUrl: "https://images.unsplash.com/photo-1534361960057-19889db9621e?ixlib=rb-4.0.3",
    features: "Fenced area,Water fountain,Shaded benches",
    distanceMiles: 1.1,
  },
  {
    id: 7,
    name: "Doggie Daylight Cafe",
    description: "Breakfast cafe with dedicated dog patio section",
    category: "cafe",
    address: "777 Sunny Ave, Downtown",
    latitude: 37.7819,
    longitude: -122.4129,
    rating: 4.6,
    reviewCount: 145,
    imageUrl: "https://images.unsplash.com/photo-1545341425-7626c6103e77?ixlib=rb-4.0.3",
    features: "Dog patio,Doggie breakfast options,Water bowls",
    distanceMiles: 0.6,
  },
  {
    id: 8,
    name: "Paws & Threads Boutique",
    description: "Pet fashion boutique that welcomes pets inside",
    category: "shop",
    address: "888 Fashion Blvd, Downtown",
    latitude: 37.7809,
    longitude: -122.4119,
    rating: 4.4,
    reviewCount: 76,
    imageUrl: "https://images.unsplash.com/photo-1598875184988-5e67b1a874b8?ixlib=rb-4.0.3",
    features: "Pets welcome inside,Fitting area,Dog treats at checkout",
    distanceMiles: 0.9,
  }
];
